name: flutter_ble_data_handler
description: A flutter package to handle bluetooth low energy data transmission.
version: 0.1.1
author: kevin@rohn.io
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: 2.1.3
  crclib: 1.0.1
  rxdart: 0.22.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true